// Lista de carros do showroom (apenas exibição — sem sistema de vendas)
const cars = [
    {
        id: 1,
        nome: "Volkswagen Golf GTI",
        categoria: "hatch",
        ano: "2023",
        km: "18.000 km",
        cambio: "Automático",
        combustivel: "Gasolina",
        cor: "Branco",
        motor: "2.0 Turbo",
        preco: "R$ 189.900",
        badge: "Seminovo",
        descricao: "Hatch esportivo com excelente desempenho e acabamento premium. Único dono, revisões em dia.",
        imagem: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=800&q=80"
    },
    {
        id: 2,
        nome: "Toyota Corolla Altis",
        categoria: "sedan",
        ano: "2024",
        km: "9.500 km",
        cambio: "CVT",
        combustivel: "Híbrido",
        cor: "Prata",
        motor: "1.8 Hybrid",
        preco: "R$ 169.900",
        badge: "Híbrido",
        descricao: "Sedã híbrido econômico e confortável. Tecnologia de ponta e baixíssimo consumo.",
        imagem: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80"
    },
    {
        id: 3,
        nome: "Jeep Compass Limited",
        categoria: "suv",
        ano: "2023",
        km: "24.000 km",
        cambio: "Automático",
        combustivel: "Diesel",
        cor: "Cinza",
        motor: "2.0 Turbo Diesel 4x4",
        preco: "R$ 209.900",
        badge: "4x4",
        descricao: "SUV robusto com tração 4x4, ideal para cidade e estrada. Interior espaçoso e tecnológico.",
        imagem: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80"
    },
    {
        id: 4,
        nome: "Toyota Hilux SRX",
        categoria: "picape",
        ano: "2022",
        km: "41.000 km",
        cambio: "Automático",
        combustivel: "Diesel",
        cor: "Preto",
        motor: "2.8 Turbo Diesel 4x4",
        preco: "R$ 279.900",
        badge: "Picape",
        descricao: "Picape de trabalho e lazer com grande capacidade de carga e robustez comprovada.",
        imagem: "https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&w=800&q=80"
    },
    {
        id: 5,
        nome: "Porsche 911 Carrera",
        categoria: "esportivo",
        ano: "2021",
        km: "12.000 km",
        cambio: "Automático PDK",
        combustivel: "Gasolina",
        cor: "Vermelho",
        motor: "3.0 Biturbo",
        preco: "R$ 899.900",
        badge: "Esportivo",
        descricao: "Ícone esportivo com desempenho excepcional. Estado impecável de colecionador.",
        imagem: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80"
    },
    {
        id: 6,
        nome: "Honda Civic Touring",
        categoria: "sedan",
        ano: "2023",
        km: "21.000 km",
        cambio: "CVT",
        combustivel: "Gasolina",
        cor: "Azul",
        motor: "1.5 Turbo",
        preco: "R$ 174.900",
        badge: "Seminovo",
        descricao: "Sedã esportivo e completo, com central multimídia e pacote de segurança avançado.",
        imagem: "https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?auto=format&fit=crop&w=800&q=80"
    },
    {
        id: 7,
        nome: "Hyundai HB20 Comfort",
        categoria: "hatch",
        ano: "2024",
        km: "6.000 km",
        cambio: "Manual",
        combustivel: "Flex",
        cor: "Branco",
        motor: "1.0 Flex",
        preco: "R$ 84.900",
        badge: "Novo",
        descricao: "Hatch compacto, econômico e ágil. Perfeito para o dia a dia na cidade.",
        imagem: "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=800&q=80"
    },
    {
        id: 8,
        nome: "Chevrolet Tracker Premier",
        categoria: "suv",
        ano: "2023",
        km: "19.000 km",
        cambio: "Automático",
        combustivel: "Flex",
        cor: "Prata",
        motor: "1.2 Turbo",
        preco: "R$ 139.900",
        badge: "SUV",
        descricao: "SUV compacto urbano com bom espaço interno e tecnologia conectada.",
        imagem: "https://images.unsplash.com/photo-1568844293986-8d0400bd4745?auto=format&fit=crop&w=800&q=80"
    }
];
